name: CI/CD Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build image Docker
        run: docker build -t cicd-nginx .

      - name: Lancer le conteneur
        run: docker run -d --name cicd-nginx -p 8080:80 cicd-nginx

      - name: Exposer avec localtunnel
        run: |
          npm install -g localtunnel
          lt --port 8080