name: CI/CD Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build image Docker
        run: docker build -t cicd-nginx .

      - name: Lancer le conteneur
        run: docker run -d --name cicd-nginx -p 8088:80 cicd-nginx

      - name: Afficher l'IP du serveur
        run: |
          IP=$(curl -s ifconfig.me)
          echo "Site accessible sur http://$IP:8088"
          sleep 120