name: CI/CD Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build image Docker
        run: docker build -t cicd-nginx .

      - name: Installer localtunnel
        run: npm install -g localtunnel

      - name: Afficher l'IP du serveur
        run: |
          IP=$(curl -s ifconfig.me)
          echo "IP du serveur : http://$IP"
          npx localtunnel --port 80 &
          sleep 10
          curl -s https://loca.lt/mytunnelpassword
          sleep 110